### ISSUE TITLE
RuntimeError - Failed to initialized graph schema

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-common#296]
When running fabric8 analytics, via `sh docker-compose.sh up`, I encounter following error every time:

```
data-model-importer_1   | [2017-09-28 08:13:34 +0000] [11] [INFO] Worker exiting (pid: 11)
data-model-importer_1   | [2017-09-28 08:13:34 +0000] [6] [INFO] Shutting down: Master
data-model-importer_1   | [2017-09-28 08:13:34 +0000] [6] [INFO] Reason: Worker failed to boot.
data-model-importer_1   | [2017-09-28 08:13:38 +0000] [6] [INFO] Starting gunicorn 19.7.1
data-model-importer_1   | [2017-09-28 08:13:38 +0000] [6] [INFO] Listening at: http://0.0.0.0:9192 (6)
data-model-importer_1   | [2017-09-28 08:13:38 +0000] [6] [INFO] Using worker: gevent
data-model-importer_1   | [2017-09-28 08:13:38 +0000] [11] [INFO] Booting worker with pid: 11
data-model-importer_1   | [2017-09-28 08:13:39 +0000] [11] [ERROR] Exception in worker process
data-model-importer_1   | Traceback (most recent call last):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
data-model-importer_1   |     worker.init_process()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
data-model-importer_1   |     super(GeventWorker, self).init_process()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
data-model-importer_1   |     self.load_wsgi()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
data-model-importer_1   |     self.wsgi = self.app.wsgi()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
data-model-importer_1   |     self.callable = self.load()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
data-model-importer_1   |     return self.load_wsgiapp()
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
data-model-importer_1   |     return util.import_app(self.app_uri)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
data-model-importer_1   |     __import__(module)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
data-model-importer_1   |     result = _import(*args, **kwargs)
data-model-importer_1   |   File "/src/rest_api.py", line 31, in <module>
data-model-importer_1   |     raise RuntimeError("Failed to initialized graph schema")
data-model-importer_1   | RuntimeError: Failed to initialized graph schema

```

**Comment by tuxdna** [comment]
The error messages are occurring because the data-model-importer web workers start before the Gremlin HTTP server is up. Since web workers depend on gremlin, schema initialization fails.
A good way is to wait for this initialization.


There are no issues with actual Schema initialization at present. However, we can benefit from some sort of checkpoints which tell us at what point the schema initialization script failed. At present the either the full script succeeds or it fails without any indication on which line number it failed to execute. 

 https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/src/schema.groovy

The later mechanism can be built-in into the Schema initialization script.
