### ISSUE TITLE
[integration-tests] Failing scenarios: features/component_search

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-common#487]
No idea what's the cause, so filling issue here.

From https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/814/console

```
Scenario: Check the component search functionality for existing component from the npm ecosystem  # features/component_search.feature:27

    Given System is running                                                                         # features/steps/common.py:38

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

    Given Component search service is running                                                       # features/steps/component_analysis.py:12

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    When I acquire the authorization token                                                          # features/steps/authorization.py:25

    Then I should get the proper authorization token                                                # features/steps/authorization.py:13

    When I search for component wisp with authorization token                                       # features/steps/component_analysis.py:43

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    Then I should find the analysis for the component wisp from ecosystem npm                       # features/steps/component_analysis.py:146

      Traceback (most recent call last):

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1456, in run

          match.run(runner.context)

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1903, in run

          self.func(context, *args, **kwargs)

        File "/tests/features/steps/component_analysis.py", line 160, in check_component_analysis_existence

          format(component=component, ecosystem=ecosystem))

      Exception: Component wisp for ecosystem npm could not be found

      

      Captured logging:

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io





  Scenario: Check the component search functionality for existing component from the pypi ecosystem  # features/component_search.feature:35

    Given System is running                                                                          # features/steps/common.py:38

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

    Given Component search service is running                                                        # features/steps/component_analysis.py:12

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    When I acquire the authorization token                                                           # features/steps/authorization.py:25

    Then I should get the proper authorization token                                                 # features/steps/authorization.py:13

    When I search for component clojure_py with authorization token                                  # features/steps/component_analysis.py:43

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    Then I should find the analysis for the component clojure_py from ecosystem pypi                 # features/steps/component_analysis.py:146

      Traceback (most recent call last):

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1456, in run

          match.run(runner.context)

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1903, in run

          self.func(context, *args, **kwargs)

        File "/tests/features/steps/component_analysis.py", line 160, in check_component_analysis_existence

          format(component=component, ecosystem=ecosystem))

      Exception: Component clojure_py for ecosystem pypi could not be found

      

      Captured logging:

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io





  Scenario: Check the component search functionality for existing component from the maven ecosystem  # features/component_search.feature:43

    Given System is running                                                                           # features/steps/common.py:38

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

    Given Component search service is running                                                         # features/steps/component_analysis.py:12

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    When I acquire the authorization token                                                            # features/steps/authorization.py:25

    Then I should get the proper authorization token                                                  # features/steps/authorization.py:13

    When I search for component vertx with authorization token                                        # features/steps/component_analysis.py:43

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

    Then I should find the analysis for the component io.vertx:vertx-core from ecosystem maven        # features/steps/component_analysis.py:146

      Traceback (most recent call last):

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1456, in run

          match.run(runner.context)

        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1903, in run

          self.func(context, *args, **kwargs)

        File "/tests/features/steps/component_analysis.py", line 160, in check_component_analysis_existence

          format(component=component, ecosystem=ecosystem))

      Exception: Component io.vertx:vertx-core for ecosystem maven could not be found

      

      Captured logging:

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io

      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.prod-preview.openshift.io
```

**Comment by tisnik** [comment]
I'll look at it.

**Comment by msrb** [comment]
Looks like it started failing here: https://ci.centos.org/view/Devtools/job/devtools-fabric8-analytics-server-f8a-build-master/120/

And it's been failing for all commits to server repository ever since.

**Comment by tisnik** [comment]
Good catch. I just added reference to this issue to the PR (already merged, though).

**Comment by miteshvp** [comment]
@msrb @tisnik - Yes, you are right. The way we do component search now has changed. I will talk to @ravsa to modify the test cases accordingly.

**Comment by msrb** [comment]
@miteshvp no worries, we should do something about CI and how it is reporting failures in E2E tests. CI was pretty unstable lately (hopefully fixed by https://github.com/openshiftio/openshiftio-cico-jobs/pull/524) and MM notifications are not targeted to specific people (hard to configure this) so I can't really blame people for ignoring them.

**Comment by tisnik** [comment]
@miteshvp thanks a lot. Please let me know if you or @ravsa would need any help with tests.
