### ISSUE TITLE
Provide better error message in e2e tests when auth token is wrong/outdated

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-common#752]
Currently the error message is not ideal:

```

Trying to retrieve access token

Exception AssertionError: Error communicating with the OSIO AUTH service

Traceback (most recent call last):

  File "/usr/bin/behave", line 11, in <module>

    sys.exit(main())

  File "/usr/lib/python3.4/site-packages/behave/__main__.py", line 109, in main

    failed = runner.run()

  File "/usr/lib/python3.4/site-packages/behave/runner.py", line 672, in run

    return self.run_with_paths()

  File "/usr/lib/python3.4/site-packages/behave/runner.py", line 693, in run_with_paths

    return self.run_model()

  File "/usr/lib/python3.4/site-packages/behave/runner.py", line 471, in run_model

    self.run_hook('before_all', context)

  File "/usr/lib/python3.4/site-packages/behave/runner.py", line 405, in run_hook

    self.hooks[name](context, *args)

  File "features/environment.py", line 582, in before_all

    os.environ.get("OSIO_AUTH_SERVICE"))

  File "features/environment.py", line 486, in retrieve_access_token

    assert response is not None and response.ok, "Error communicating with the OSIO AUTH service"

AssertionError: Error communicating with the OSIO AUTH service
```

It would be nice to improve it and tell users what happened.

**Comment by tisnik** [comment]
Already merged into the `environment.py`
